### ISSUE TITLE
Exception not well handled

### ISSUE THREAD

**Issue by dxli94** [agiledigital/poet-slack-bot#11]
When the question is not understood, should not throw a nullPointer exception.

@sabiipoks 

Try ask "people on POET-3?" or "Description of POET-3".

Instead of surrounding with try-catch, I believe it is better to add these and similar words to the keyword list.

**Comment by hasanniz** [comment]
Issues (this section) is meant for users of the git repo who want to report bugs or ask for a feature. Use slack or JIRA comments for communicating instead.
