### ISSUE TITLE
LUIS setup and configuration.

### ISSUE THREAD

**Issue by haolinj** [agiledigital/poet-slack-bot#33]
Hi @dongxuDX , can you please provide some instructions on how to setup the LUIS for the POET? I think currently we cannot use POET at all if LUIS is not setup properly, i.e. LUIS intent, Entities configuration.

If you can share your demo LUIS intents and Entities, that be great. Thanks.

**Comment by dxli94** [comment]
Please see email. Thanks.

**Comment by haolinj** [comment]
@dongxuDX When did you send the email? Can you please re-send the email of the LUIS configuration you used for demo (final presentation)? 

Also, if you can, can you please push latest code of the POET (you guys used in the final presentation), I think the current master branch is missing a lot of features.

**Comment by dxli94** [comment]
Please, see the email I sent just now. Thanks.

**Comment by haolinj** [comment]
@dongxuDX Which email address you have sent to?

**Comment by dxli94** [comment]
jira.support@agiledigital.com.au. Or can you please update me the correct one?

**Comment by haolinj** [comment]
@dongxuDX  please send to hljiang@agiledigital.com.au

Also, do you have the latest code that used in your final presentation?

**Comment by dxli94** [comment]
@haolinj  Sent! Regarding the code, please see the mail, too.

**Comment by haolinj** [comment]
Received the emails, thanks.
